baseURL = "/"
title = "NTP: Network Time Protocol"

enableRobotsTXT = true

  # CSS Plugins
  [[params.plugins.css]]
  link = "https://necolas.github.io/normalize.css/latest/normalize.css"
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  
# Preloader
  [params.preloader]
  preloader = "" # use .png , .svg or .gif format

# Language settings
contentDir = "content/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[params]
copyright = "Network Time Foundation"
logo1 = "images/ntp_logo.jpg"
logo2 = "images/logo.png"

github_repo = "https://github.com/ntp-project/ntp"
prism_syntax_highlighting = false

[params.ui]
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it!</a>'
no = 'Sorry to hear that.</a>'

[params.links]
[[params.links.user]]
	name = "Mailing lists"
	url = "https://lists.ntp.org/listinfo"
	icon = "bi-envelope"
        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/ntp"
	icon = "bi-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name ="LinkedIn"
	url = "https://www.linkedin.com/groups/4651343"
	icon = "bi-linkedin"
        desc = "Follow us on LinkedIn"
[[params.links.user]]
	name = "Facebook"
	url = "https://www.facebook.com/networktimeprotocol"
	icon = "bi-facebook"
        desc = "Follow us on Facebook"
		
[languages]
[languages.en]
contentDir = "content/en"
title = "NTP: Network Time Protocol"
description = "NTP Documentation Archive"
languageName ="English"
# Weight used for sorting.
weight = 1
[[languages.en.menu.main]]
    name = "Reference Library"
    url = "/reflib"
    weight = 20
    hasChildren = true
	  [[languages.en.menu.main]] 
	  parent = "Reference Library"
	  name = "Briefs"
	  URL = "/reflib/brief"
	  weight = 1
	  [[languages.en.menu.main]] 
	  parent = "Reference Library"
	  name = "Memos"
	  URL = "/reflib/memos"
	  weight = 2
	  [[languages.en.menu.main]] 
	  parent = "Reference Library"
	  name = "Reports"
	  URL = "/reflib/reports"
	  weight = 3
	  [[languages.en.menu.main]] 
	  parent = "Reference Library"
	  name = "RFCs"
	  URL = "/reflib/rfc"
	  weight = 4
	  [[languages.en.menu.main]] 
	  parent = "Reference Library"
	  name = "Software"
	  URL = "/reflib/software"
	  weight = 5
	  [[languages.en.menu.main]] 
	  parent = "Reference Library"
	  name = "White Papers"
	  URL = "/reflib/papers"
	  weight = 6

[[languages.en.menu.main]]
    name = "Docs"
    url = "/archives"
    weight = 30
    hasChildren = true
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "4.2.8-series"
	  URL = "/archives/4.2.8-series/toc"
	  weight = 1
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "4.2.6-series"
	  URL = "/archives/4.2.6-series/toc"
	  weight = 2
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "4.2.4-series"
	  URL = "/archives/4.2.4-series/toc"
	  weight = 3
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "4.2.2-series"
	  URL = "/archives/4.2.2-series/toc"
	  weight = 4
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "4.2.0"
	  URL = "/archives/4.2.0/toc"
	  weight = 5
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "4.1.2"
	  URL = "/archives/4.1.2/toc"
	  weight = 6
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "4.1.1"
	  URL = "/archives/4.1.1/toc"
	  weight = 7
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "4.1.0"
	  URL = "/archives/4.1.0/toc"
	  weight = 8
	  [[languages.en.menu.main]] 
	  parent = "Docs"
	  name = "3-5.93e"
	  URL = "/archives/3-5.93e/toc"
	  weight = 9

[languages.de]
languageName ="Deutsch"
contentDir = "content/de"
weight = 2
[[languages.de.menu]]
[[languages.de.menu.main]]
    name = "Präsenzbibliothek"
    url = "/reflib"
    weight = 20
    hasChildren = true
	  [[languages.de.menu.main]] 
	  parent = "Präsenzbibliothek"
	  name = "Auftrage"
	  URL = "/reflib/brief"
	  weight = 1
	  [[languages.de.menu.main]] 
	  parent = "Präsenzbibliothek"
	  name = "Memos"
	  URL = "/reflib/memos"
	  weight = 2
	  [[languages.de.menu.main]] 
	  parent = "Präsenzbibliothek"
	  name = "Berichte "
	  URL = "/reflib/reports"
	  weight = 3
	  [[languages.de.menu.main]] 
	  parent = "Präsenzbibliothek"
	  name = "RFCs"
	  URL = "/reflib/rfc"
	  weight = 4
	  [[languages.de.menu.main]] 
	  parent = "Präsenzbibliothek"
	  name = "Software"
	  URL = "/reflib/software"
	  weight = 5
	  [[languages.de.menu.main]] 
	  parent = "Präsenzbibliothek"
	  name = "Weiße Papiere"
	  URL = "/reflib/papers"
	  weight = 6

[[languages.de.menu.main]]
    name = "Dokumente"
    url = "/archives"
    weight = 30
    hasChildren = true
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "4.2.8-serie"
	  URL = "/archives/4.2.8-series/toc"
	  weight = 1
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "4.2.6-serie"
	  URL = "/archives/4.2.6-series/toc"
	  weight = 2
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "4.2.4-serie"
	  URL = "/archives/4.2.4-series/toc"
	  weight = 3
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "4.2.2-series"
	  URL = "/archives/4.2.2-series/toc"
	  weight = 4
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "4.2.0"
	  URL = "/archives/4.2.0/toc"
	  weight = 5
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "4.1.2"
	  URL = "/archives/4.1.2/toc"
	  weight = 6
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "4.1.1"
	  URL = "/archives/4.1.1/toc"
	  weight = 7
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "4.1.0"
	  URL = "/archives/4.1.0/toc"
	  weight = 8
	  [[languages.de.menu.main]] 
	  parent = "Dokumente"
	  name = "3-5.93e"
	  URL = "/archives/3-5.93e/toc"
	  weight = 9

[languages.ja]
languageName ="日本"
contentDir = "content/ja"
weight = 3
[[languages.ja.menu]]
[[languages.ja.menu.main]]
    name = "リファレンスライブラリ "
    url = "/reflib"
    weight = 20
    hasChildren = true
	  [[languages.ja.menu.main]] 
	  parent = "リファレンスライブラリ "
	  name = "梗概"
	  URL = "/reflib/brief"
	  weight = 1
	  [[languages.ja.menu.main]] 
	  parent = "リファレンスライブラリ "
	  name = "メモ"
	  URL = "/reflib/memos"
	  weight = 2
	  [[languages.ja.menu.main]] 
	  parent = "リファレンスライブラリ "
	  name = "レポート "
	  URL = "/reflib/reports"
	  weight = 3
	  [[languages.ja.menu.main]] 
	  parent = "リファレンスライブラリ "
	  name = "RFCs"
	  URL = "/reflib/rfc"
	  weight = 4
	  [[languages.ja.menu.main]] 
	  parent = "リファレンスライブラリ "
	  name = "ソフトウェア"
	  URL = "/reflib/software"
	  weight = 5
	  [[languages.ja.menu.main]] 
	  parent = "リファレンスライブラリ "
	  name = "白い紙"
	  URL = "/reflib/papers"
	  weight = 6

[[languages.ja.menu.main]]
    name = "ドキュメント "
    url = "/archives"
    weight = 30
    hasChildren = true
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "4.2.8-シリーズ"
	  URL = "/archives/4.2.8-series/toc"
	  weight = 1
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "4.2.6-シリーズ"
	  URL = "/archives/4.2.6-series/toc"
	  weight = 2
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "4.2.4-シリーズ"
	  URL = "/archives/4.2.4-series/toc"
	  weight = 3
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "4.2.2-シリーズ"
	  URL = "/archives/4.2.2-series/toc"
	  weight = 4
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "4.2.0"
	  URL = "/archives/4.2.0/toc"
	  weight = 5
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "4.1.2"
	  URL = "/archives/4.1.2/toc"
	  weight = 6
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "4.1.1"
	  URL = "/archives/4.1.1/toc"
	  weight = 7
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "4.1.0"
	  URL = "/archives/4.1.0/toc"
	  weight = 8
	  [[languages.ja.menu.main]] 
	  parent = "ドキュメント"
	  name = "3-5.93e"
	  URL = "/archives/3-5.93e/toc"
	  weight = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"